apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraopsTest
  labels:
    app: infraopsTest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraopsTest
  template:
    metadata:
      labels:
        app: infraopsTest
    spec:
      containers:
        - name: infraopsTest
          image: techwarrior007/infraopsTest:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/bookdb
            - name: SPRING_DATASOURCE_USERNAME
              value: bookuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: bookpassword
