version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpassword
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bookdb
      SPRING_DATASOURCE_USERNAME: bookuser
      SPRING_DATASOURCE_PASSWORD: bookpassword
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
